import{a as h,S as m,i as u}from"./assets/vendor-09d7c26e.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function t(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(o){if(o.ep)return;o.ep=!0;const r=t(o);fetch(o.href,r)}})();const y="42772780-849d5e67a8b9b0ab7e6b7483b",g="https://pixabay.com/api/",p={async fetchImages(e,s=1,t=15){try{const n=await h.get(g,{params:{key:y,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:t}});return n.data.hits.length===0?{hits:[],totalHits:0}:n.data}catch(n){throw console.error("Error fetching images:",n),new Error("Failed to fetch images from Pixabay API")}}};function L(e){const s=document.querySelector(".gallery"),t=document.querySelector(".load-more-btn");if(!s||!t){console.error("Gallery list or Load more button not found");return}const n=e.map(r=>`
    <li class="gallery-item">
      <a href="${r.largeImageURL}" class="gallery-link">
        <img src="${r.webformatURL}" alt="${r.tags}" class="gallery-image" />
      </a>
      <div class="gallery-item-info">
        <div class="info-item">Likes: ${r.likes}</div>
        <div class="info-item">Views: ${r.views}</div>
        <div class="info-item">Comments: ${r.comments}</div>
        <div class="info-item">Downloads: ${r.downloads}</div>
      </div>
    </li>
  `).join("");s.innerHTML+=n,new m(".gallery a").refresh(),e.length>0&&t.classList.remove("hidden")}function b(){const e=document.querySelector(".gallery");e?e.innerHTML="":console.error("Gallery list not found")}function v(){const e=document.querySelector(".loader");e?e.classList.add("visible"):console.error("Loader not found")}function w(){const e=document.querySelector(".loader");e?e.classList.remove("visible"):console.error("Loader not found")}function E(e){console.error("Error:",e),S("An error occurred. Please try again later.")}function S(e){u.error({title:"Error",message:e})}function d(){u.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})}const q=document.querySelector(".search-form"),l=document.querySelector(".load-more-btn");let a=1,i="";async function f(e,s){try{v();const t=await p.fetchImages(e,s);if(t.hits.length===0){d(),l.classList.add("hidden");return}L(t.hits),(t.hits.length<15||t.hits.length+(s-1)*15>=t.totalHits)&&(l.classList.add("hidden"),t.hits.length+(s-1)*15>=t.totalHits&&d());const n=document.querySelectorAll(".gallery-item");if(n.length){const{height:o}=n[0].getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}catch(t){console.error("Error fetching images:",t),E(t)}finally{w()}}q.addEventListener("submit",async e=>{e.preventDefault();const t=e.target.querySelector(".search-input").value.trim();t&&t!==i&&(i=t,a=1,b(),l.classList.add("hidden"),await f(i,a))});l.addEventListener("click",async()=>{a+=1,await f(i,a)});
//# sourceMappingURL=commonHelpers.js.map
