import{a as f,S as m,i as d}from"./assets/vendor-09d7c26e.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function t(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(o){if(o.ep)return;o.ep=!0;const r=t(o);fetch(o.href,r)}})();const h="42772780-849d5e67a8b9b0ab7e6b7483b",y="https://pixabay.com/api/",g={async fetchImages(e,s=1,t=15){try{const n=await f.get(y,{params:{key:h,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:t}});if(n.data.hits.length===0)throw new Error("No images found");return n.data}catch(n){throw console.error("Error fetching images:",n),n}}};function p(e){const s=document.querySelector(".gallery"),t=document.querySelector(".load-more-btn");if(!s||!t){console.error("Gallery list or Load more button not found");return}const n=e.map(r=>`
    <li class="gallery-item">
      <a href="${r.largeImageURL}" class="gallery-link">
        <img src="${r.webformatURL}" alt="${r.tags}" class="gallery-image" />
      </a>
      <div class="gallery-item-info">
        <div class="info-item">Likes: ${r.likes}</div>
        <div class="info-item">Views: ${r.views}</div>
        <div class="info-item">Comments: ${r.comments}</div>
        <div class="info-item">Downloads: ${r.downloads}</div>
      </div>
    </li>
  `).join("");s.innerHTML+=n,new m(".gallery a").refresh(),e.length>0&&t.classList.remove("hidden")}function L(){const e=document.querySelector(".gallery");e?e.innerHTML="":console.error("Gallery list not found")}function b(){const e=document.querySelector(".loader");e?e.classList.add("visible"):console.error("Loader not found")}function v(){const e=document.querySelector(".loader");e?e.classList.remove("visible"):console.error("Loader not found")}function w(e){console.error("Error:",e),S("An error occurred. Please try again later.")}function S(e){d.error({title:"Error",message:e})}function q(){d.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})}const E=document.querySelector(".search-form"),c=document.querySelector(".load-more-btn");let l=1,i="";async function u(e,s){try{b();const t=await g.fetchImages(e,s);p(t.hits),v(),(t.hits.length<15||t.hits.length+(s-1)*15>=t.totalHits)&&(c.classList.add("hidden"),t.hits.length+(s-1)*15>=t.totalHits&&q());const n=document.querySelectorAll(".gallery-item");if(n.length){const{height:o}=n[0].getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}catch(t){w(t)}}E.addEventListener("submit",async e=>{e.preventDefault();const t=e.target.querySelector(".search-input").value.trim();t&&t!==i&&(i=t,l=1,L(),c.classList.add("hidden"),await u(i,l))});c.addEventListener("click",async()=>{l+=1,await u(i,l)});
//# sourceMappingURL=commonHelpers.js.map
